AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda with Function URL
Resources:
  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: my-lambda-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-python-lambda
      Runtime: python3.14
      Handler: lambda_handler.lambda_handler
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Code:
        S3Bucket: my-todo-lambda-artifacts-123456
        S3Key: lambda.zip
  MyLambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn:
        Ref: MyLambdaFunction
      AuthType: NONE
  LambdaUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: MyLambdaFunction
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: MyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: '*'
      InvokedViaFunctionUrl: true
