name: CI/CD Pipeline

on:
  pull_request:
  push:
    branches: [ main ]

env:
  AWS_REGION : "ap-southeast-2"
  ROLE_TO_ASSUME: arn:aws:iam::495671352507:role/github

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest

    # 👇 THIS is the key part
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Deploy CloudFormation
        run: |
          aws cloudformation deploy \
            --stack-name IAC \
            --template-file infra/sth.yaml \
            --capabilities CAPABILITY_NAMED_IAM